[package]
name = "lambda-router-tests"
version = "0.1.2"
edition = "2021"

[lib]

[dependencies]
lambda-router = { version = "0.1.5", path = "../lambda-router" }
lambda_http = "0.11.1"
serde = { version = "1.0.200", features = ["derive"] }
