[package]
name = "lambda-router-tests"
version = "0.1.1"
edition = "2021"

[lib]

[dependencies]
lambda-router = { version = "0.1.2", path = "../lambda-router" }
lambda_http = "0.9.2"
serde = { version = "1.0.188", features = ["derive"] }
